import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { Roboto } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // You can customize weights
  variable: "--font-roboto",     // Custom CSS variable
});

export const metadata = {
  title: "KrishCarbon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Navbar />
        {children}

      </body>
    </html>
  );
}
